name: encryption_decryption
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  auto_size_widget: ^0.0.4
  bitsdojo_window: ^0.1.5
  dropdown_button2: ^1.9.2
  encrypt: ^5.0.1
  fast_rsa: ^3.5.3
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  path_provider: ^2.0.12
  selectable: ^0.2.11
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  

flutter:
  uses-material-design: true
  assets:
    - assets/
