name: encryption_decryption
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_size_text_field: ^2.2.1
  bitsdojo_window: ^0.1.5
  dropdown_button2: ^1.9.2
  encrypt: ^5.0.1
  fast_rsa: ^3.5.3
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  path_provider: ^2.0.12
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
